DATA_PATH = "data"

DATE_FORMAT = "%Y-%m-%d"

ASSET_DAILY_PARTITION_START_DATE = "2023-12-01"
ASSET_DAILY_PARTITION_END_DATE = "2023-12-05"

DAILY_GROUP = "daily"
RAW_GROUP = "raw"
LOOKUP_GROUP = "lookup"

OBSERVE_INTERVAL_MINUTES = 60
